/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorrespondenceRouteImport } from './routes/correspondence'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FirmsRouteImport } from './routes/firms'
import { Route as HouseRouteImport } from './routes/house'
import { Route as InductionRouteImport } from './routes/induction'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasteryRouteImport } from './routes/mastery'
import { Route as PerformersRouteImport } from './routes/performers'
import { Route as RealitiesRouteImport } from './routes/realities'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StreetRouteImport } from './routes/street'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CorrespondenceIdRouteImport } from './routes/correspondence.$id'
import { Route as HouseAlertsRouteImport } from './routes/house.alerts'
import { Route as HousePipelineRouteImport } from './routes/house.pipeline'
import { Route as HousePortfolioRouteImport } from './routes/house.portfolio'
import { Route as HouseRoomsRouteImport } from './routes/house.rooms'
import { Route as HouseSeatsRouteImport } from './routes/house.seats'
import { Route as LadderRankRouteImport } from './routes/ladder.$rank'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as StreetHighlightsRouteImport } from './routes/street.highlights'
import { Route as StreetQualityRouteImport } from './routes/street.quality'
import { Route as StreetSpreadRouteImport } from './routes/street.spread'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HouseRoomsIdRouteImport } from './routes/house.rooms.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceRoute = CorrespondenceRouteImport.update({
  id: '/correspondence',
  path: '/correspondence',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsRoute = FirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const InductionRoute = InductionRouteImport.update({
  id: '/induction',
  path: '/induction',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasteryRoute = MasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformersRoute = PerformersRouteImport.update({
  id: '/performers',
  path: '/performers',
  getParentRoute: () => rootRouteImport,
} as any)
const RealitiesRoute = RealitiesRouteImport.update({
  id: '/realities',
  path: '/realities',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetRoute = StreetRouteImport.update({
  id: '/street',
  path: '/street',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceIdRoute = CorrespondenceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CorrespondenceRoute,
} as any)
const HouseAlertsRoute = HouseAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => HouseRoute,
} as any)
const HousePipelineRoute = HousePipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => HouseRoute,
} as any)
const HousePortfolioRoute = HousePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => HouseRoute,
} as any)
const HouseRoomsRoute = HouseRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => HouseRoute,
} as any)
const HouseSeatsRoute = HouseSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => HouseRoute,
} as any)
const LadderRankRoute = LadderRankRouteImport.update({
  id: '/$rank',
  path: '/$rank',
  getParentRoute: () => LadderRoute,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchRoute,
} as any)
const StreetHighlightsRoute = StreetHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => StreetRoute,
} as any)
const StreetQualityRoute = StreetQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => StreetRoute,
} as any)
const StreetSpreadRoute = StreetSpreadRouteImport.update({
  id: '/spread',
  path: '/spread',
  getParentRoute: () => StreetRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoomsIdRoute = HouseRoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HouseRoomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/house': typeof HouseRouteWithChildren
  '/induction': typeof InductionRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/street': typeof StreetRouteWithChildren
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/house/alerts': typeof HouseAlertsRoute
  '/house/pipeline': typeof HousePipelineRoute
  '/house/portfolio': typeof HousePortfolioRoute
  '/house/rooms': typeof HouseRoomsRouteWithChildren
  '/house/seats': typeof HouseSeatsRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/research/$id': typeof ResearchIdRoute
  '/street/highlights': typeof StreetHighlightsRoute
  '/street/quality': typeof StreetQualityRoute
  '/street/spread': typeof StreetSpreadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/house/rooms/$id': typeof HouseRoomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/house': typeof HouseRouteWithChildren
  '/induction': typeof InductionRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/street': typeof StreetRouteWithChildren
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/house/alerts': typeof HouseAlertsRoute
  '/house/pipeline': typeof HousePipelineRoute
  '/house/portfolio': typeof HousePortfolioRoute
  '/house/rooms': typeof HouseRoomsRouteWithChildren
  '/house/seats': typeof HouseSeatsRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/research/$id': typeof ResearchIdRoute
  '/street/highlights': typeof StreetHighlightsRoute
  '/street/quality': typeof StreetQualityRoute
  '/street/spread': typeof StreetSpreadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/house/rooms/$id': typeof HouseRoomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/house': typeof HouseRouteWithChildren
  '/induction': typeof InductionRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/research': typeof ResearchRouteWithChildren
  '/signup': typeof SignupRoute
  '/street': typeof StreetRouteWithChildren
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/house/alerts': typeof HouseAlertsRoute
  '/house/pipeline': typeof HousePipelineRoute
  '/house/portfolio': typeof HousePortfolioRoute
  '/house/rooms': typeof HouseRoomsRouteWithChildren
  '/house/seats': typeof HouseSeatsRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/research/$id': typeof ResearchIdRoute
  '/street/highlights': typeof StreetHighlightsRoute
  '/street/quality': typeof StreetQualityRoute
  '/street/spread': typeof StreetSpreadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/house/rooms/$id': typeof HouseRoomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/house'
    | '/induction'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/research'
    | '/signup'
    | '/street'
    | '/studio'
    | '/correspondence/$id'
    | '/house/alerts'
    | '/house/pipeline'
    | '/house/portfolio'
    | '/house/rooms'
    | '/house/seats'
    | '/ladder/$rank'
    | '/research/$id'
    | '/street/highlights'
    | '/street/quality'
    | '/street/spread'
    | '/api/auth/$'
    | '/house/rooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/house'
    | '/induction'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/research'
    | '/signup'
    | '/street'
    | '/studio'
    | '/correspondence/$id'
    | '/house/alerts'
    | '/house/pipeline'
    | '/house/portfolio'
    | '/house/rooms'
    | '/house/seats'
    | '/ladder/$rank'
    | '/research/$id'
    | '/street/highlights'
    | '/street/quality'
    | '/street/spread'
    | '/api/auth/$'
    | '/house/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/house'
    | '/induction'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/research'
    | '/signup'
    | '/street'
    | '/studio'
    | '/correspondence/$id'
    | '/house/alerts'
    | '/house/pipeline'
    | '/house/portfolio'
    | '/house/rooms'
    | '/house/seats'
    | '/ladder/$rank'
    | '/research/$id'
    | '/street/highlights'
    | '/street/quality'
    | '/street/spread'
    | '/api/auth/$'
    | '/house/rooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorrespondenceRoute: typeof CorrespondenceRouteWithChildren
  DeskRoute: typeof DeskRoute
  FirmsRoute: typeof FirmsRoute
  HouseRoute: typeof HouseRouteWithChildren
  InductionRoute: typeof InductionRoute
  LadderRoute: typeof LadderRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasteryRoute: typeof MasteryRoute
  PerformersRoute: typeof PerformersRoute
  RealitiesRoute: typeof RealitiesRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SignupRoute: typeof SignupRoute
  StreetRoute: typeof StreetRouteWithChildren
  StudioRoute: typeof StudioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence': {
      id: '/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms': {
      id: '/firms'
      path: '/firms'
      fullPath: '/firms'
      preLoaderRoute: typeof FirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/induction': {
      id: '/induction'
      path: '/induction'
      fullPath: '/induction'
      preLoaderRoute: typeof InductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mastery': {
      id: '/mastery'
      path: '/mastery'
      fullPath: '/mastery'
      preLoaderRoute: typeof MasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performers': {
      id: '/performers'
      path: '/performers'
      fullPath: '/performers'
      preLoaderRoute: typeof PerformersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realities': {
      id: '/realities'
      path: '/realities'
      fullPath: '/realities'
      preLoaderRoute: typeof RealitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/street': {
      id: '/street'
      path: '/street'
      fullPath: '/street'
      preLoaderRoute: typeof StreetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence/$id': {
      id: '/correspondence/$id'
      path: '/$id'
      fullPath: '/correspondence/$id'
      preLoaderRoute: typeof CorrespondenceIdRouteImport
      parentRoute: typeof CorrespondenceRoute
    }
    '/house/alerts': {
      id: '/house/alerts'
      path: '/alerts'
      fullPath: '/house/alerts'
      preLoaderRoute: typeof HouseAlertsRouteImport
      parentRoute: typeof HouseRoute
    }
    '/house/pipeline': {
      id: '/house/pipeline'
      path: '/pipeline'
      fullPath: '/house/pipeline'
      preLoaderRoute: typeof HousePipelineRouteImport
      parentRoute: typeof HouseRoute
    }
    '/house/portfolio': {
      id: '/house/portfolio'
      path: '/portfolio'
      fullPath: '/house/portfolio'
      preLoaderRoute: typeof HousePortfolioRouteImport
      parentRoute: typeof HouseRoute
    }
    '/house/rooms': {
      id: '/house/rooms'
      path: '/rooms'
      fullPath: '/house/rooms'
      preLoaderRoute: typeof HouseRoomsRouteImport
      parentRoute: typeof HouseRoute
    }
    '/house/seats': {
      id: '/house/seats'
      path: '/seats'
      fullPath: '/house/seats'
      preLoaderRoute: typeof HouseSeatsRouteImport
      parentRoute: typeof HouseRoute
    }
    '/ladder/$rank': {
      id: '/ladder/$rank'
      path: '/$rank'
      fullPath: '/ladder/$rank'
      preLoaderRoute: typeof LadderRankRouteImport
      parentRoute: typeof LadderRoute
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/street/highlights': {
      id: '/street/highlights'
      path: '/highlights'
      fullPath: '/street/highlights'
      preLoaderRoute: typeof StreetHighlightsRouteImport
      parentRoute: typeof StreetRoute
    }
    '/street/quality': {
      id: '/street/quality'
      path: '/quality'
      fullPath: '/street/quality'
      preLoaderRoute: typeof StreetQualityRouteImport
      parentRoute: typeof StreetRoute
    }
    '/street/spread': {
      id: '/street/spread'
      path: '/spread'
      fullPath: '/street/spread'
      preLoaderRoute: typeof StreetSpreadRouteImport
      parentRoute: typeof StreetRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/rooms/$id': {
      id: '/house/rooms/$id'
      path: '/$id'
      fullPath: '/house/rooms/$id'
      preLoaderRoute: typeof HouseRoomsIdRouteImport
      parentRoute: typeof HouseRoomsRoute
    }
  }
}

interface CorrespondenceRouteChildren {
  CorrespondenceIdRoute: typeof CorrespondenceIdRoute
}

const CorrespondenceRouteChildren: CorrespondenceRouteChildren = {
  CorrespondenceIdRoute: CorrespondenceIdRoute,
}

const CorrespondenceRouteWithChildren = CorrespondenceRoute._addFileChildren(
  CorrespondenceRouteChildren,
)

interface HouseRoomsRouteChildren {
  HouseRoomsIdRoute: typeof HouseRoomsIdRoute
}

const HouseRoomsRouteChildren: HouseRoomsRouteChildren = {
  HouseRoomsIdRoute: HouseRoomsIdRoute,
}

const HouseRoomsRouteWithChildren = HouseRoomsRoute._addFileChildren(
  HouseRoomsRouteChildren,
)

interface HouseRouteChildren {
  HouseAlertsRoute: typeof HouseAlertsRoute
  HousePipelineRoute: typeof HousePipelineRoute
  HousePortfolioRoute: typeof HousePortfolioRoute
  HouseRoomsRoute: typeof HouseRoomsRouteWithChildren
  HouseSeatsRoute: typeof HouseSeatsRoute
}

const HouseRouteChildren: HouseRouteChildren = {
  HouseAlertsRoute: HouseAlertsRoute,
  HousePipelineRoute: HousePipelineRoute,
  HousePortfolioRoute: HousePortfolioRoute,
  HouseRoomsRoute: HouseRoomsRouteWithChildren,
  HouseSeatsRoute: HouseSeatsRoute,
}

const HouseRouteWithChildren = HouseRoute._addFileChildren(HouseRouteChildren)

interface LadderRouteChildren {
  LadderRankRoute: typeof LadderRankRoute
}

const LadderRouteChildren: LadderRouteChildren = {
  LadderRankRoute: LadderRankRoute,
}

const LadderRouteWithChildren =
  LadderRoute._addFileChildren(LadderRouteChildren)

interface ResearchRouteChildren {
  ResearchIdRoute: typeof ResearchIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchIdRoute: ResearchIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface StreetRouteChildren {
  StreetHighlightsRoute: typeof StreetHighlightsRoute
  StreetQualityRoute: typeof StreetQualityRoute
  StreetSpreadRoute: typeof StreetSpreadRoute
}

const StreetRouteChildren: StreetRouteChildren = {
  StreetHighlightsRoute: StreetHighlightsRoute,
  StreetQualityRoute: StreetQualityRoute,
  StreetSpreadRoute: StreetSpreadRoute,
}

const StreetRouteWithChildren =
  StreetRoute._addFileChildren(StreetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorrespondenceRoute: CorrespondenceRouteWithChildren,
  DeskRoute: DeskRoute,
  FirmsRoute: FirmsRoute,
  HouseRoute: HouseRouteWithChildren,
  InductionRoute: InductionRoute,
  LadderRoute: LadderRouteWithChildren,
  LoginRoute: LoginRoute,
  MasteryRoute: MasteryRoute,
  PerformersRoute: PerformersRoute,
  RealitiesRoute: RealitiesRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SignupRoute: SignupRoute,
  StreetRoute: StreetRouteWithChildren,
  StudioRoute: StudioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
