/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorrespondenceRouteImport } from './routes/correspondence'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FirmsRouteImport } from './routes/firms'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasteryRouteImport } from './routes/mastery'
import { Route as PerformersRouteImport } from './routes/performers'
import { Route as RealitiesRouteImport } from './routes/realities'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CorrespondenceIdRouteImport } from './routes/correspondence.$id'
import { Route as LadderRankRouteImport } from './routes/ladder.$rank'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceRoute = CorrespondenceRouteImport.update({
  id: '/correspondence',
  path: '/correspondence',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsRoute = FirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasteryRoute = MasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformersRoute = PerformersRouteImport.update({
  id: '/performers',
  path: '/performers',
  getParentRoute: () => rootRouteImport,
} as any)
const RealitiesRoute = RealitiesRouteImport.update({
  id: '/realities',
  path: '/realities',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceIdRoute = CorrespondenceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CorrespondenceRoute,
} as any)
const LadderRankRoute = LadderRankRouteImport.update({
  id: '/$rank',
  path: '/$rank',
  getParentRoute: () => LadderRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/correspondence': typeof CorrespondenceRouteWithChildren
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/ladder': typeof LadderRouteWithChildren
  '/login': typeof LoginRoute
  '/mastery': typeof MasteryRoute
  '/performers': typeof PerformersRoute
  '/realities': typeof RealitiesRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/correspondence/$id': typeof CorrespondenceIdRoute
  '/ladder/$rank': typeof LadderRankRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/signup'
    | '/studio'
    | '/correspondence/$id'
    | '/ladder/$rank'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/signup'
    | '/studio'
    | '/correspondence/$id'
    | '/ladder/$rank'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/correspondence'
    | '/desk'
    | '/firms'
    | '/ladder'
    | '/login'
    | '/mastery'
    | '/performers'
    | '/realities'
    | '/signup'
    | '/studio'
    | '/correspondence/$id'
    | '/ladder/$rank'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorrespondenceRoute: typeof CorrespondenceRouteWithChildren
  DeskRoute: typeof DeskRoute
  FirmsRoute: typeof FirmsRoute
  LadderRoute: typeof LadderRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasteryRoute: typeof MasteryRoute
  PerformersRoute: typeof PerformersRoute
  RealitiesRoute: typeof RealitiesRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence': {
      id: '/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms': {
      id: '/firms'
      path: '/firms'
      fullPath: '/firms'
      preLoaderRoute: typeof FirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mastery': {
      id: '/mastery'
      path: '/mastery'
      fullPath: '/mastery'
      preLoaderRoute: typeof MasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performers': {
      id: '/performers'
      path: '/performers'
      fullPath: '/performers'
      preLoaderRoute: typeof PerformersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realities': {
      id: '/realities'
      path: '/realities'
      fullPath: '/realities'
      preLoaderRoute: typeof RealitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence/$id': {
      id: '/correspondence/$id'
      path: '/$id'
      fullPath: '/correspondence/$id'
      preLoaderRoute: typeof CorrespondenceIdRouteImport
      parentRoute: typeof CorrespondenceRoute
    }
    '/ladder/$rank': {
      id: '/ladder/$rank'
      path: '/$rank'
      fullPath: '/ladder/$rank'
      preLoaderRoute: typeof LadderRankRouteImport
      parentRoute: typeof LadderRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CorrespondenceRouteChildren {
  CorrespondenceIdRoute: typeof CorrespondenceIdRoute
}

const CorrespondenceRouteChildren: CorrespondenceRouteChildren = {
  CorrespondenceIdRoute: CorrespondenceIdRoute,
}

const CorrespondenceRouteWithChildren = CorrespondenceRoute._addFileChildren(
  CorrespondenceRouteChildren,
)

interface LadderRouteChildren {
  LadderRankRoute: typeof LadderRankRoute
}

const LadderRouteChildren: LadderRouteChildren = {
  LadderRankRoute: LadderRankRoute,
}

const LadderRouteWithChildren =
  LadderRoute._addFileChildren(LadderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorrespondenceRoute: CorrespondenceRouteWithChildren,
  DeskRoute: DeskRoute,
  FirmsRoute: FirmsRoute,
  LadderRoute: LadderRouteWithChildren,
  LoginRoute: LoginRoute,
  MasteryRoute: MasteryRoute,
  PerformersRoute: PerformersRoute,
  RealitiesRoute: RealitiesRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
